### ISSUE TITLE
Have a way to edit existing law or policy source

### ISSUE THREAD

**Issue by jhung** [fluid-project/lcil#10]
From the view page of a law / policy source, the user should be able to edit information about the law and policy source. This includes:
* Name
* Reference
* Type
* etc.

The user should be able to delete a law and policy source as well (#11 ).

Functional spec for edit existing law / policy source can be found here: https://github.com/fluid-project/lcil/wiki/v0.1-Functional-Spec#edit-law-or-policy-source

**Comment by jobara** [comment]
Route info:

- `/sources/{source}`
  - **Description:** Save updates to a law or policy source
  - **HTTP Method:** `PUT`/`PATCH`
  - **CRUD Operation:** Update
  - **RESTful Action:** Update
- `/sources/{source}`
  - **Description:** Remove law or policy source from the database
  - **HTTP Method:** `DELETE`
  - **CRUD Operation:** Delete
  - **RESTful Action:** Destroy
- `/sources/{source}/edit`
  - **Description:** Display the page for editing a law or policy source
  - **HTTP Method:** `GET`
  - **CRUD Operation:** Read
  - **RESTful Action:** Edit

**Comment by jobara** [comment]
In order to better represent the actual resource being accessed and avoid duplication the new suggestion for the URL is.

`/law-policy-sources/{country}/{province}/{municipality}/{year}/{slug}`

- `{country}` required
- `{province}` optional
- `{municipality}` optional
- `{year}` required
- `{slug}`required

Missing required fields will result in a 404 and/or redirect to the law and policy source landing page. The path will assume the first segment is the country, the second last is the year, the last is the slug, and the optional ones coming in the order they are specified in the url (i.e. you can't specify a municipality without a province).

The `slug` will be the slugified version of the law and policy source's name.

**Comment by jobara** [comment]
Deletion will be addressed with #65
