### ISSUE TITLE
Have a way to edit Provisions for a law or policy source

### ISSUE THREAD

**Issue by jhung** [fluid-project/lcil#12]
Have a way for someone to be able to edit provisions for a law or policy source. The user can choose which provision to edit or delete (#11), or add a new provision (#8).

Functional spec for editing a provision can be found here:
https://github.com/fluid-project/lcil/wiki/v0.1-Functional-Spec#edit-provision

**Comment by jobara** [comment]
Route info:

- `/sources/{source}/{provision}`
  - **Description:** Save updates to the provision on the database
  - **HTTP Method:** `PUT`/`PATCH`
  - **CRUD Operation:** Update
  - **RESTful Action:** Update
- `/sources/{source}/{provision}`
  - **Description:** Remove the provision from the database
  - **HTTP Method:** `DELETE`
  - **CRUD Operation:** Delete
  - **RESTful Action:** Destroy
- `/sources/{source}/{provision}/edit`
  - **Description:** Display the page for editing a provision
  - **HTTP Method:** `GET`
  - **CRUD Operation:** Read
  - **RESTful Action:** Edit

**Comment by jobara** [comment]
In order to better represent the actual resource being accessed and avoid duplication the new suggestion for the URL is.

`/law-policy-sources/{country}/{province}/{municipality}/{year}/{slug}`

- `{country}` required
- `{province}` optional
- `{municipality}` optional
- `{year}` required
- `{slug}`required

Missing required fields will result in a 404 and/or redirect to the law and policy source landing page. The path will assume the first segment is the country, the second last is the year, the last is the slug, and the optional ones coming in the order they are specified in the url (i.e. you can't specify a municipality without a province).

The `slug` will be the slugified version of the law and policy source's name.

**Comment by jobara** [comment]
Deletion will be addressed with #66
