### ISSUE TITLE
Implement the Regime Assessment Summary (view) page

### ISSUE THREAD

**Issue by jhung** [fluid-project/lcil#22]
Implement the Regime Assessment Summary view page. This page will allow the user to:
* review measures
* choose which measure to evaluate
* go to specific sources of law and policy

If the user has permissions, they will have links to pages that will allow them to edit content (i.e. evaluations, sources of law and policy, and regime assessment details).

Related to #23.

**Comment by jobara** [comment]
Route info:

- `/assessments/{assessment}`
  - **Description:** Display a specific Regime Assessment
  - **HTTP Method:** `GET`
  - **CRUD Operation:** Read
  - **RESTful Action:** Show

**Comment by jobara** [comment]
In order to better represent the actual resource being accessed and avoid duplication the new suggestion for the URL is.

`/regime-assessmenta/{country}/{province}/local/{year}/{slug}`

- `{country}` required
- `{province}` optional
- `{municipality}` optional
- `{year}` required
- `{slug}`required

Missing required fields will result in a 404 and/or redirect to the regime assessments landing page. The path will assume the first segment is the country, the second last is the year, the last is the slug, and the optional ones coming in the order they are specified in the url (i.e. you can't specify a municipality without a province).

The `slug` will be the Regime Assessment code/id (e.g. RA-11042020-1 which corresponds to RA-DDMMYYYY-#).
