### ISSUE TITLE
Implement Edit Regime Assessment page

### ISSUE THREAD

**Issue by jhung** [fluid-project/lcil#25]
Implement the Edit Regime Assessment page so the user can edit:
* jurisdiction
* effective date
* sources of law and policy
* etc.

![image](https://user-images.githubusercontent.com/564762/160475787-f0b1e904-d869-488c-a50b-0f27d800945d.png)

Design of this page depends on #20.

**Comment by jobara** [comment]
Route info:

- `/assessments/{assessment}`
  - **Description:** Save updates to a Regime Assent to the database
  - **HTTP Method:** `PUT`/`PATCH`
  - **CRUD Operation:** Update
  - **RESTful Action:** Update
- `/assessments/{assessment}`
  - **Description:** Remove Regime Assessment from the database
  - **HTTP Method:** `DELETE`
  - **CRUD Operation:** Delete
  - **RESTful Action:** Destroy
- `/assessments/{assessment}/edit`
  - **Description:** Display the page for editing a Regime Assessment
  - **HTTP Method:** `GET`
  - **CRUD Operation:** Read
  - **RESTful Action:** Edit

**Comment by jobara** [comment]
In order to better represent the actual resource being accessed and avoid duplication the new suggestion for the URL is.

`/regime-assessments/{country}/{province}/local/{year}/{slug}`

- `{country}` required
- `{province}` optional
- `{municipality}` optional
- `{year}` required
- `{slug}`required

Missing required fields will result in a 404 and/or redirect to the regime assessments landing page. The path will assume the first segment is the country, the second last is the year, the last is the slug, and the optional ones coming in the order they are specified in the url (i.e. you can't specify a municipality without a province).

The `slug` will be the Regime Assessment code/id (e.g. RA-20200411-1 which corresponds to RA-YYYYMMDD-#).

**Comment by jobara** [comment]
Deletion will be addressed with #67
