### ISSUE TITLE
Implement adding provisions to an existing law or policy source

### ISSUE THREAD

**Issue by jhung** [fluid-project/lcil#8]
Have a way to add provisions to a law / policy source. This includes:
* section or subsection
* Provision text
* Reference (i.e. an URL)
* Type of decision
* Provision has been subject to a constitutional / court challenge
* Provision is the result of a court challenge
* Decision citation

The user can submit, submit and add more,cancel, or skip adding a provision.

If the user is creating a new law and policy source, the add provision form will include extra information to provide context and workflow options (i.e. Go back to edit law and policy source, and skip this step).

The functional spec can be found here: https://github.com/fluid-project/lcil/wiki/v0.1-Functional-Spec#create-provision

**Comment by jobara** [comment]
Route info:

- `/sources/{source}`
  - **Description:** Create a provision in the database
  - **HTTP Method:** `POST`
  - **CRUD Operation:** Create
  - **RESTful Action:** Store
- `/sources/{source}/create`
  - **Description:** Display the page for creating provision
  - **HTTP Method:** `GET`
  - **CRUD Operation:** Read
  - **RESTful Action:** Create

**Comment by jobara** [comment]
In order to better represent the actual resource being accessed and avoid duplication the new suggestion for the URL is.

`/law-policy-sources/{country}/{province}/{municipality}/{year}/{slug}`

- `{country}` required
- `{province}` optional
- `{municipality}` optional
- `{year}` required
- `{slug}`required

Missing required fields will result in a 404 and/or redirect to the law and policy source landing page. The path will assume the first segment is the country, the second last is the year, the last is the slug, and the optional ones coming in the order they are specified in the url (i.e. you can't specify a municipality without a province).

The `slug` will be the slugified version of the law and policy source's name.

**Comment by jobara** [comment]
The URL for a Law and Policy source is now `/law-policy-souces/{lawPolicySoure}` the slug for a law and policy source is jurisdiction-name converted into a URL safe slug format. The URLs for the provision should be:

- *create:* `/law-policy-sources/{lawPolicySource}/create`
- *store:* `/law-policy-sources/{lawPolicySource}`
