### ISSUE TITLE
Have a way to view a law or policy source

### ISSUE THREAD

**Issue by jhung** [fluid-project/lcil#9]
Have a way to view an existing law and policy source. This page will display law and policy source information (i.e. name, year in effect, jurisdiction, etc), and the provisions specified.

There will be links to edit the law or policy source, and add / delete / edit provisions.

![image](https://user-images.githubusercontent.com/564762/160451886-0d42a259-8201-4f84-9326-ab454d9f34d4.png)

**Comment by jobara** [comment]
Route info:

- `/sources/{source}`
  - **Description:** Display a specific law or policy source; includes list of associated provisions
  - **HTTP Method:** `GET`
  - **CRUD Operation:** Read
  - **RESTful Action:** Show

**Comment by jobara** [comment]
In order to better represent the actual resource being accessed and avoid duplication the new suggestion for the URL is.

`/lawpolicy/{country}/{province}/{municipality}/{year}/{slug}`

- `{country}` required
- `{province}` optional
- `{municipality}` optional
- `{year}` required
- `{slug}`required

Missing required fields will result in a 404 and/or redirect to the law and policy source landing page. The path will assume the first segment is the country, the second last is the year, the last is the slug, and the optional ones coming in the order they are specified in the url (i.e. you can't specify a municipality without a province).

The `slug` will be the slugified version of the law and policy source's name.
